name: build-and-test
on:
  workflow_dispatch:
    inputs:
      publish:
        required: true
      version:
        required: false
        default: minor
jobs:
  build-and-test-linux:
    defaults:
      run:
        working-directory: "~/salesforcedx-apex"
    runs-on: sfdc-hk-ubuntu-latest
    container:
      image: node:lts
    steps:
    - uses: actions/checkout@v2
    - name: restore_cache
      uses: actions/cache@v2
      with:
        key: dependency-cache-linux-{{ checksum "yarn.lock" }}
        path: node_modules
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test_with_coverage
    - uses: actions/upload-artifact@v2
      with:
        path:  "~/salesforcedx-apex/."
  build-and-test-win:
    runs-on: sfdc-hk-ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: restore_cache
      uses: actions/cache@v2
      with:
        key: dependency-cache-win-{{ checksum "yarn.lock" }}
        path: node_modules
    - run: yarn install --frozen-lockfile
    - name: Setup workspace Symlinks for Windows
      run: yarn windowsCopySymlinks
    - name: Run tests on windows (Without coverage)
      run: yarn test
